spring: 
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.238:8818:orcl
    username: market
    password: market2018
  jpa:
    show-sql: true 
  redis:
    database: 1
    host: 192.168.1.238
    port: 6379
    password: quantu%78@ksdf!
    timeout: 2000
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0  
device:
  uri: http://wlw.quantwo.cn:2007/api/v1/device/
  query: 
    method: get_state
  turn-on: 
    method: turn_on
  turn-off: 
    method: turn_off
o2: 
  wechat:
    subscription:  
      app: 
        id: wx93953fe379a2c548
        secret: 883fcd2427e25e9c00600af8a664fb87