metadata:
  eureka:
    hostname: localhost

server:
  port: 8888
spring:
  application:
    name: eureka-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${metadata.eureka.hostname}:${server.port}/eureka/
      
endpoints:
  shutdown:
    enabled: true
    sensitive: false
# 安全认证的配置  
security:  
  basic:  
    enabled: true  
  user:  
    name: quantu  # 用户名  
    password: eh6N2L9P   # 用户密码  