server:
  port: 5555
spring:
  application:
    name: eureka-service
  profiles: peer3
eureka:
  client:
    fetch-registry: true #是否检索服务
    register-with-eureka: true
    service-url:
      defaultZone: http://quantu:eh6N2L9P@peer1:3333/eureka/,http://quantu:eh6N2L9P@peer2:4444/eureka/
  instance:
    hostname: peer3
    appname: eureka-service
    prefer-ip-address: false
endpoints:
  shutdown:
    enabled: true
    sensitive: false
# 安全认证的配置  
security:  
  basic:  
    enabled: true  
  user:  
    name: quantu  # 用户名  
    password: eh6N2L9P   # 用户密码  