spring: 
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.13.202:1521:orcl
    username: market
    password: market2018
  jpa:
    show-sql: true
  redis:
    database: 1
    host: 192.168.13.202
    port: 6379
    password: 
    timeout: 2000
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0   
device:
  uri: http://wlw.quantwo.cn:2007/api/v1/device/
  query: 
    method: get_state
  turn-on: 
    method: turn_on
  turn-off: 
    method: turn_off
o2: 
  weixin: 
    cache:  
      name: weixinCacheDefine
  wechat:
    cert: 
      stream:
        path: /cer/apiclient_cert.p12
    subscription: 
      body:
        description: 圈兔圈网络-空气净化器
      notify: 
        url: http://zf.quantwo.cn/device/billing/notify
      mah:
        id: 1511610321
      app: 
        id: wx93953fe379a2c548
        secret: 883fcd2427e25e9c00600af8a664fb87
      api: 
        secret: quantuztwyzl39quantwoquantuztwyz
  system:
    domain: http://quantwo.cn/app.html