spring: 
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.238:8819:orcl
    username: market
    password: market2018
  jpa:
    show-sql: true
device:
  uri: http://192.168.1.236:2007/api/v1/device/
  query: 
    method: get_state
  turn-on: 
    method: turn_on
  turn-off: 
    method: turn_off
  pm25:
    method: pm25