spring: 
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.100:1521:orcl
    username: market
    password: market2018
  jpa:
    show-sql: true   
  redis:
    database: 1
    host: 192.168.1.100
    port: 6379
    password: 
    timeout: 2000
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0